name: saudi_clean_services
description: Saudi Clean Services

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.14
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  shared_preferences: ^2.0.15
  flutter_rating_bar: ^4.0.1
  multiselect: ^0.0.7
  url_launcher: ^6.1.7
  intl: ^0.18.0
  location: ^4.4.0
  tuple: ^2.0.1
  flutter_svg: ^1.1.6
  flutter_credit_card: ^3.0.4
  sliding_sheet: ^0.5.2
  lottie: ^2.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.11.0

#adding the splash screen
flutter_native_splash:
  background_image: assets/images/splash.png

#adding the app icon
flutter_icons:
  android: true
  ios: true
  image_path: assets/images/app_logo.jpg



flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/splash.png
    - assets/images/app_logo.jpg
    - assets/images/background.jpg
    - assets/images/icons/google.png
    - assets/images/ads.png
    - assets/images/offer.png
    - assets/images/icons/Bronze.svg
    - assets/images/icons/Silver.svg
    - assets/images/icons/Gold.svg
    - assets/images/icons/Diamond.svg
    - assets/images/icons/paypal.png
    - assets/images/icons/master_card.png
    - assets/images/icons/visa_card.png
    - assets/images/icons/google_pay.png
    - assets/images/icons/pay_cash.png
    - assets/lottie/done.json


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700



